export const LOGINPAGE = {
  heading: "The experience of ordering food quickly",
  subHeading: "We serve quality, the true taste of trust",
  signUp: "Sign up",
  login: "Login",
  or: "OR",
  welcome: "Welcome back !",
  foodie: "Let’s get login foodiee",
  username: "Username",
  star: "*",
  password: "Password",
  namePlaceholder: "Enter your username . . .",
  pwdPlaceholder: "Enter your password . . .",
  forgot: "Forgot Password",
  remember: "Remember me",
  toast: "Incorrect username/password, Please try again",
  noAccount: "Don’t have any account?",
};

export const ADDTOCART = {
  add: "ADD",
  plus: "+",
  minus: "-",
};

export const HOMESCREEN = {
  location: "Location",
  geo: "3096 Wilkinson Street, USA",
  search: "Search . . .",
  main: "Main course",
  noItem: "No item to display",
  showMore: "Show all Menu",
  cuisine: "Our special cuisine",
  offer: "Exclusive offer for you",
  rating: "5.0",
  reviews: "(1,895 Reviews)",
  coupon: "Use coupon code",
  code: "BURGER50",
  offerCuisine: "to get 50% OFF on your order",
};

export const PRODUCTDESCRIPTION = [
  {
    description:
      "A Two flame-grilled beef patty with crunchy pickles, yellow mustard, and ketchup on a toasted sesame seed bun.",
    serving: "30 Min | 1 Serving",
    product_cost: 10,
    product_discounted_cost: "8.80",
    name: "Classic Hamburger",
    rating: "4.4",
    reviews: "(395 Reviews)",
    readmore: "Read More",
    ingredients: "Top Ingredients",
    ingredientCount: 4,
    id: "1236",
    facts: "Nutrition Facts",
    allergen: "Allergen Information",
    suballergen: "Thick Cut Applewood Smoked Bacon",
    descallergen:
      "Ingredients: Beef Patty, Crunchy pickles, Yellow mustard, Ketchup, Toasted Sesame Seed Bun, Cream and Salt.",
    salted: "Salted Butter",
    items: "Ingredients: Cream, Salt.",
    images: require("../assets/svgImages/burgerImage.jpg"),
  },
  {
    description:
      "Fried Chicken nugget is a food product consisting of a small piece of deboned chicken Meat that is breaded or battered, then deep-fried or baked.",
    serving: "25 Min | 2 Serving",
    name: "Fried Chicken Nuggets",
    rating: "4.2",
    reviews: "(189 Reviews)",
    product_cost: 16,
    product_discounted_cost: "15.20",
    readmore: "Read More",
    ingredients: "Top Ingredients",
    ingredientCount: 2,
    id: "1234",
    facts: "Nutrition Facts",
    allergen: "Allergen Information",
    suballergen: "Thick Cut Applewood Smoked Bacon",
    descallergen: "Ingredients: Nuggets, Ketchup",
    salted: "Salted Butter",
    items: "Ingredients: Cream, Salt.",
    images: require("../assets/svgImages/chickenNuggets.png"),
  },
  {
    description:
      "Crisp shredded lettuce and three Roma tomato slices top deliciously juicy and cooked when you order. Seasoned with just a pinch of salt and pepper and sizzled on our flat iron grill. Layered with two slices of melty American cheese, creamy mayo, slivered onions and tangy pickles on a soft, fluffy sesame seed hamburger bun",
    serving: "28 Min | 1 Serving",
    name: "Double Cheeseburger Deluxe",
    id: "1235",
    rating: "4.6",
    product_cost: 13,
    product_discounted_cost: "13.40",
    reviews: "(582 Reviews)",
    readmore: "Read More",
    ingredients: "Top Ingredients",
    ingredientCount: 4,
    facts: "Nutrition Facts",
    allergen: "Allergen Information",
    suballergen: "Thick Cut Applewood Smoked Bacon",
    descallergen:
      "Ingredients: Beef Patty, Bun, American Cheese- Pasteurized, Tomato, Ketchup, Shredded Lettuce, Pickle Slices, Onions, Mustard",
    salted: "Salted Butter",
    items: "Ingredients: Mustard, Salt.",
    images: require("../assets/svgImages/Burger2.png"),
  },
];

export const CART = {
  cart: "Order Cart",
  order: "Your Order",
  benefits: "Offers & Benefits",
  coupon: "Apply Coupon",
  save: "Save",
  with: "with",
  code: "TRYNEW",
  subTotal: "Subtotal:",
  tax: "Tax & charges:",
  appliedCoupon: "Coupon -",
  appliedCode: "TRYNEW",
  button: "Proceed to Pay",
  serving: "2 serving",
};

export const PAYMENT = {
  payment: "Payment",
  bill: "Bill Total",
  saved: "Saved Cards",
  online: "Choose other ways to pay",
  other: "Others",
  safe: "Safe and Secured payments. Easy Returns. 100% Authentic products",
  paypal: "PayPal Wallet",
  gpay: "Google Pay",
  ipay: "Apple Pay",
  cod: "Pay on delivery",
  eligible: "Eligible for Single Click Payment",
};

export const CONFIRMATION = {
  awesome: "Awesome !",
  accepted: "Your order is accepted !",
  patience: "Your order will be prepared in",
  min: " 23 minutes. ",
  trackNavigation: "Click here",
  later: " to track your order.",
  message: "This will help us to serve you better in near future !!",
  redirected: "You will be redirected in",
  sec: "sec",
};
