/*
{
  "data": {
    "foodReducer": {
      "amount": 0,
      "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywidXNlcl9uYW1lIjoiYWRtaW4iLCJ1c2VyX3JvbGUiOiJhZG1pbiIsInVzZXJfcm9sZV9pZCI6MiwicGVybWlzc2lvbnMiOlsiR2V0X1VzZXIiLCJFZGl0X1VzZXIiLCJDcmVhdGVfVXNlciIsIkRlbGV0ZV9Vc2VyIiwiR2V0X0ludmVudG9yeSIsIkVkaXRfSW52ZW50b3J5IiwiQ3JlYXRlX0ludmVudG9yeSIsIkRlbGV0ZV9JbnZlbnRvcnkiLCJHZXRfT3JkZXIiLCJFZGl0X09yZGVyIiwiQ3JlYXRlX09yZGVyIiwiRGVsZXRlX09yZGVyIiwiR2V0X1Byb2R1Y3QiLCJFZGl0X1Byb2R1Y3QiLCJHZXRfU2NoZWR1bGUiLCJFZGl0X1NjaGVkdWxlIiwiR2V0X05vdGlmaWNhdGlvbiIsIkVkaXRfTm90aWZpY2F0aW9uIiwiR2V0X1N1YnNjcmlwdGlvbiIsIkVkaXRfU3Vic2NyaXB0aW9uIl0sImV4cGlyZXMiOjE2Njc2MzYxNDUuMjIxMjU4Mn0.6jZo3FuTLnbb4IlO4R0YneF84biXTdtukyIrH3q8xx0",
      "chatNumber": 0,
      "foodItems": {
          "1": {
            "active_from": "2022-11-02T12:30:32.327941",
            "active_till": "2025-07-29T12:30:32.327945",
            "category": "Burgers",
            "cuisine": "American",
            "description": "Its topped off with pickles, crisp shredded lettuce, finely chopped onion and American cheese for a 100% beef burger with a taste like no other. ",
            "food_class": "Non-Veg",
            "id": 1,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/78/Jumbo_Burger.jpg",
            "product_cost": 4,
            "product_discounted_cost": 2,
            "product_name": "Jumbo Burger",
            "quantity": 1,
            "temperature_max": 72,
            "temperature_min": 50,
            "updated_by": "admin"
          },
          "2": {
            "active_from": "2022-11-02T12:30:32.327958",
            "active_till": "2025-07-29T12:30:32.327959",
            "category": "Burgers",
            "cuisine": "Chinese",
            "description": "Big bacon cheese, are a mini-quiche mix of spicy cheeses, and topped with bacon ",
            "food_class": "Non-Veg",
            "id": 2,
            "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd58jAWu4HvD5M2hgUExYSc_czpvsIEEo-eA&usqp=CAU",
            "product_cost": 4,
            "product_discounted_cost": 2,
            "product_name": "Big Bacon Cheeseburger",
            "quantity": 1,
            "temperature_max": 72,
            "temperature_min": 50,
            "updated_by": "admin"
          },
          "3": {
            "active_from": "2022-11-02T12:30:32.327962",
            "active_till": "2025-07-29T12:30:32.327963",
            "category": "Burgers",
            "cuisine": "American",
            "description": "Spicy Pepper Sauce topping the southern style fried chicken fillet on a toasted potato roll, this sandwich was made for those who like it crispy, juicy, tender and hot.",
            "food_class": "Non-Veg",
            "id": 3,
            "image_url": "https://easykitchen.com/wp-content/uploads/2016/04/pan-fried-spicy-chicken-sandwiches-670x405.jpg",
            "product_cost": 4,
            "product_discounted_cost": 2,
            "product_name": "Chilli Crispy chicken Sandwich",
            "quantity": 1,
            "temperature_max": 70,
            "temperature_min": 60,
            "updated_by": "admin"
          }
        },
      "orderID": ""
    },
    "product": {
      "index": 0,
      "productItems": [
        {
          "active_from": "2022-11-02T12:30:32.327941",
          "active_till": "2025-07-29T12:30:32.327945",
          "category": "Burgers",
          "cuisine": "American",
          "description": "Its topped off with pickles, crisp shredded lettuce, finely chopped onion and American cheese for a 100% beef burger with a taste like no other. ",
          "food_class": "Non-Veg",
          "id": 1,
          "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/78/Jumbo_Burger.jpg",
          "product_cost": 4,
          "product_discounted_cost": 2,
          "product_name": "Jumbo Burger",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327958",
          "active_till": "2025-07-29T12:30:32.327959",
          "category": "Burgers",
          "cuisine": "Chinese",
          "description": "Big bacon cheese, are a mini-quiche mix of spicy cheeses, and topped with bacon ",
          "food_class": "Non-Veg",
          "id": 2,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd58jAWu4HvD5M2hgUExYSc_czpvsIEEo-eA&usqp=CAU",
          "product_cost": 4,
          "product_discounted_cost": 2,
          "product_name": "Big Bacon Cheeseburger",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327962",
          "active_till": "2025-07-29T12:30:32.327963",
          "category": "Burgers",
          "cuisine": "American",
          "description": "Spicy Pepper Sauce topping the southern style fried chicken fillet on a toasted potato roll, this sandwich was made for those who like it crispy, juicy, tender and hot.",
          "food_class": "Non-Veg",
          "id": 3,
          "image_url": "https://easykitchen.com/wp-content/uploads/2016/04/pan-fried-spicy-chicken-sandwiches-670x405.jpg",
          "product_cost": 4,
          "product_discounted_cost": 2,
          "product_name": "Chilli Crispy chicken Sandwich",
          "temperature_max": 70,
          "temperature_min": 60,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327966",
          "active_till": "2025-07-29T12:30:32.327967",
          "category": "Burgers",
          "cuisine": "American",
          "description": "Crisp shredded lettuce and three Roma tomato slices top deliciously juicy and cooked when you order. Seasoned with just a pinch of salt and pepper and sizzled on our flat iron grill. Layered with two slices of melty American cheese, creamy mayo, slivered onions and tangy pickles on a soft, fluffy sesame seed hamburger bun",
          "food_class": "Veg",
          "id": 4,
          "image_url": "https://loveincorporated.blob.core.windows.net/contentimages/gallery/c40174f1-72e7-4f09-999b-a761a86f9c7b-two_cheese_deluxe_dq.jpg",
          "product_cost": 5,
          "product_discounted_cost": 2,
          "product_name": "Double Cheeseburger Deluxe",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327970",
          "active_till": "2025-07-29T12:30:32.327971",
          "category": "Burgers",
          "cuisine": "American",
          "description": "The patties are very unique and is prepared mainly with mashed potatoes and green peas. the flagship mcaloo tikki recipe from McDonalds involves a special sauce which is basically a combination of tomato sauce and mayonnaise.",
          "food_class": "Non-Veg",
          "id": 5,
          "image_url": "https://wpcdn.us-east-1.vip.tn-cloud.net/www.sactownmag.com/content/uploads/data-import/38bc9265/BaconFest_TankHouse.jpg",
          "product_cost": 5,
          "product_discounted_cost": 2,
          "product_name": "Bacon feast",
          "temperature_max": 75,
          "temperature_min": 60,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327974",
          "active_till": "2025-07-29T12:30:32.327975",
          "category": "Burgers",
          "cuisine": "American",
          "description": "It's made with mayo on the outside for perfectly browned and crispy bread on the outside yet it was tender soft on the inside.",
          "food_class": "Veg",
          "id": 6,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRACTWYATkdV1HXr2MSjUgsmr1_Kq5QFUuaHw&usqp=CAU",
          "product_cost": 3,
          "product_discounted_cost": 2,
          "product_name": "Cheeseburger",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.327996",
          "active_till": "2025-07-29T12:30:32.327998",
          "category": "Burgers",
          "cuisine": "American",
          "description": "A Two flame-grilled beef patty with crunchy pickles, yellow mustard, and ketchup on a toasted sesame seed bun.",
          "food_class": "Non-Veg",
          "id": 7,
          "image_url": "https://d21klxpge3tttg.cloudfront.net/wp-content/uploads/2013/05/featured-great-american-hamburger.jpg",
          "product_cost": 2,
          "product_discounted_cost": 2,
          "product_name": "Classic Hamburger",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328002",
          "active_till": "2025-07-29T12:30:32.328003",
          "category": "Burgers",
          "cuisine": "American",
          "description": ".Two flame-grilled Cheese Burger with juicy tomatoes,cheese",
          "food_class": "Veg",
          "id": 8,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhPV6gntbyQZoOIhx2eOu4LCU3_HhIADbXAw&usqp=CAU",
          "product_cost": 3,
          "product_discounted_cost": 1,
          "product_name": "Deluxe Hamburger",
          "temperature_max": 72,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328006",
          "active_till": "2025-07-29T12:30:32.328007",
          "category": "Sides",
          "cuisine": "American",
          "description": "They are prepared by cutting potatoes into even strips, drying them, and frying them, usually in a deep fryer. Pre-cut, blanched, and frozen russet potatoes are widely used, and sometimes baked in a regular or convection oven",
          "food_class": "Veg",
          "id": 9,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEq9e24xNPCMB0Un7fEp4J3w0QE51RTPp_tg&usqp=CAU",
          "product_cost": 1,
          "product_discounted_cost": 3,
          "product_name": "Fries",
          "temperature_max": 50,
          "temperature_min": 40,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328010",
          "active_till": "2025-07-29T12:30:32.328011",
          "category": "Sides",
          "cuisine": "American",
          "description": "A cross-sectional ring of onion dipped in batter or bread crumbs and then deep fried; a variant is made with onion paste",
          "food_class": "Veg",
          "id": 10,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8JZWYj2zBhCBT7-r0hy_waYWfMKz4t_Pafg&usqp=CAU",
          "product_cost": 1,
          "product_discounted_cost": 3,
          "product_name": "Onion rings",
          "temperature_max": 50,
          "temperature_min": 40,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328014",
          "active_till": "2025-07-29T12:30:32.328015",
          "category": "Sides",
          "cuisine": "American",
          "description": "Fried Chicken nugget is a food product consisting of a small piece of deboned chicken Meat that is breaded or battered, then deep-fried or baked.",
          "food_class": "Non-Veg",
          "id": 11,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmKncfEL0r_P5f0DrdptQLoqo4-eHwiXnHKw&usqp=CAU",
          "product_cost": 4,
          "product_discounted_cost": 2,
          "product_name": "Fried Chicken Nuggets",
          "temperature_max": 60,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328018",
          "active_till": "2025-07-29T12:30:32.328019",
          "category": "Sides",
          "cuisine": "American",
          "description": "Light and crispy bites, filled with roaster cheddar cheese.",
          "food_class": "Non-Veg",
          "id": 12,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG256re4IRb3JVt8m2vVtTjZ9EzvpBWVeQxg&usqp=CAU",
          "product_cost": 2,
          "product_discounted_cost": 2,
          "product_name": "Roasted Special Cheddar Bites",
          "temperature_max": 50,
          "temperature_min": 40,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328022",
          "active_till": "2025-07-29T12:30:32.328023",
          "category": "Drinks",
          "cuisine": "European",
          "description": "100% Natural applesauce from all natural ingredients with no added sugar. Contains 1 full serving of fruit, is naturally",
          "food_class": "Veg",
          "id": 13,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsQSJ4M-EL3XCSbErShAT8zrw4IWmtUYH5-Q&usqp=CAU",
          "product_cost": 1,
          "product_discounted_cost": 1,
          "product_name": "Greek AppleSauce",
          "temperature_max": 20,
          "temperature_min": 15,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328025",
          "active_till": "2025-07-29T12:30:32.328026",
          "category": "Drinks",
          "cuisine": "Indian",
          "description": "Try the Double Loaded Chocolate shake, the perfect sweet treat for any time of the day. Our chocolate shake is made with delicious soft serve, chocolate syrup and finished off with a creamy whipped topping. Double Loaded Chocolate shake is available in small, medium and large.",
          "food_class": "Veg",
          "id": 14,
          "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaaJfcUQ2BqzxzJVP3_foiGAE1w2gf_MulXw&usqp=CAU",
          "product_cost": 1,
          "product_discounted_cost": 1,
          "product_name": "Double Loaded Chocolate shake",
          "temperature_max": 10,
          "temperature_min": 5,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328029",
          "active_till": "2025-07-29T12:30:32.328030",
          "category": "Drinks",
          "cuisine": "American",
          "description": "reat yourself to a Butter Caramel Sundae! This Caramel Sundae combines creamy vanilla soft serve and warm, buttery caramel topping.",
          "food_class": "Veg",
          "id": 15,
          "image_url": "https://thumbs.dreamstime.com/b/mud-sundae-pecans-top-drizzled-caramel-sauce-33730895.jpg",
          "product_cost": 1,
          "product_discounted_cost": 1,
          "product_name": "Buttery Caramel Sundae",
          "temperature_max": 20,
          "temperature_min": 15,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328033",
          "active_till": "2025-07-29T12:30:32.328034",
          "category": "Drinks",
          "cuisine": "American",
          "description": "Diet Cola is the perfect balance of crisp + refreshing. it’s your deliciously fizzy go-to companion. the beverage you can count on. an original, just like you.",
          "food_class": "Veg",
          "id": 16,
          "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/10/Glass_cola.jpg",
          "product_cost": 3,
          "product_discounted_cost": 3,
          "product_name": "Diet Cola",
          "temperature_max": 10,
          "temperature_min": 5,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328036",
          "active_till": "2025-07-29T12:30:32.328038",
          "category": "Drinks",
          "cuisine": "American",
          "description": "Diet Coke is the perfect balance of crisp + refreshing. it’s your deliciously fizzy go-to companion. the beverage you can count on. an original, just like you.",
          "food_class": "Veg",
          "id": 17,
          "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/10/Glass_cola.jpg",
          "product_cost": 3,
          "product_discounted_cost": 3,
          "product_name": "Diet Coke",
          "temperature_max": 10,
          "temperature_min": 5,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328040",
          "active_till": "2025-07-29T12:30:32.328041",
          "category": "Drinks",
          "cuisine": "American",
          "description": "Diet Pepsi is the perfect balance of crisp + refreshing. it’s your deliciously fizzy go-to companion. the beverage you can count on. an original, just like you.",
          "food_class": "Veg",
          "id": 18,
          "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/10/Glass_cola.jpg",
          "product_cost": 3,
          "product_discounted_cost": 3,
          "product_name": "Diet Pepsi",
          "temperature_max": 10,
          "temperature_min": 5,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328043",
          "active_till": "2025-07-29T12:30:32.328044",
          "category": "Drinks",
          "cuisine": "Chinese",
          "description": "This special unsweetened combination of peach and nectarine flavors plus green tea adds a delicious sparkle of nourishment to your day.",
          "food_class": "Veg",
          "id": 19,
          "image_url": "https://images.csmonitor.com/csm/2016/06/987911_1_0704_Food_NectarineIcedTea_standard.jpg?alias=standard_900x600",
          "product_cost": 1,
          "product_discounted_cost": 1,
          "product_name": "Unsweetened Nectarine Tea",
          "temperature_max": 60,
          "temperature_min": 50,
          "updated_by": "admin"
        },
        {
          "active_from": "2022-11-02T12:30:32.328047",
          "active_till": "2025-07-29T12:30:32.328048",
          "category": "Drinks",
          "cuisine": "Indian",
          "description": "Mocha  Blended Cold Coffee, milk and ice all come together for a mocha flavor that'll leave you wanting more. To change things up, try it affogato-style with a hot espresso shot poured right over the top.",
          "food_class": "Veg",
          "id": 20,
          "image_url": "https://cdnimg.webstaurantstore.com/images/products/large/107019/2070216.jpg",
          "product_cost": 2,
          "product_discounted_cost": 1,
          "product_name": "Mocha Blended Cold Coffee",
          "temperature_max": 10,
          "temperature_min": 5,
          "updated_by": "admin"
        }
      ],
      "recommended": []
    }
  }
}
*/
